name: Cancel redundant workflows
on:
  workflow_run:
    # workflows:
      # - Test  # TODO: delete this and see if it's optional
    types:
      - requested

jobs:
  cancel-redundant-workflows:
    runs-on: ubuntu-18.04
    steps:
      - uses: potiuk/cancel-workflow-runs@master
        name: "Cancel duplicate workflow runs"
        with:
          cancelMode: duplicates
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
