name: Cancel redundant workflows
on:
  workflow_run:
    workflows:
      - Test  # TODO: delete this and see if it's optional
    types:
      - requested

jobs:
  cancel-redundant-workflows:
    runs-on: ubuntu-18.04
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
        env:
          TARGET_RUN_ID: ${{ github.event.workflow_run.id }}
