name: Cancel redundant workflows
on:
  workflow_run:
    workflows: # this is not optional
      - Test
    types:
      - requested

jobs:
  cancel:
    if: github.event.workflow_run.head_branch != 'master'
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel duplicate workflow runs
        uses: potiuk/cancel-workflow-runs@v4_8
        with:
          cancelMode: duplicates
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
