name: Cancel redundant workflows
on:
  workflow_run:
    workflows: # this is not optional
      - Test
    types:
      - requested

jobs:
  cancel-redundant-workflows:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel redundant workflows
        uses: technote-space/auto-cancel-redundant-workflow@v1
        with:
          TARGET_RUN_ID: ${{ github.event.workflow_run.id }}
